version: "3.9"

services:
  api-next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-next1
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: "production"
      PORT: "3001"
    volumes:
      - api_next_data:/app/data
    restart: unless-stopped

volumes:
  api_next_data:
